name: Build RPMs
on: [push]
jobs:
  build:
    strategy:
      matrix:
        version: [2.4, 2.9]
        cpu: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: |
          make USE_PROMETHEUS=1 MAINVERSION=${{ matrix.version }} CPU=${{ matrix.cpu }} run-docker
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "RPMS/**/haproxy-2*.rpm"
          replacesArtifacts: false
          allowUpdates: true
